### ISSUE TITLE
user_trades not returning data for some markets 

### ISSUE THREAD

**Issue by npomfret** [exmo-dev/exmo_api_lib#13]
I'm not getting any results back for certain markets.  When I 

POST to `https://api.exmo.com/v1/user_trades/` with body`nonce=1525339107569000&pair=KICK_ETH` I get `{"KICK_ETH":[]}`, yet I can see plenty of deals in the website in this market.  Other markets names do work fine.

**Comment by exmo-dev** [comment]
try https://support.exmoney.com/hc/en-us/requests/new
