### ISSUE TITLE
Здравствуйте, а можно увидеть jquery версию на конкретном примере, например метод "trades", не требующий авторизации, что бы было ясно куда что подставлять. 

### ISSUE THREAD

**Issue by SpaceVision** [exmo-dev/exmo_api_lib#14]

**Comment by avelrl** [comment]
`
$.ajax({
            url: 'https://api.exmo.com/v1/trades/?pair=BTC_USD',
            type: 'get',
            dataType: 'json',
            success: function (data) {
                $( "#result" ).append( "<p>"+JSON.stringify(data)+"</p>" );
            }
        });
`

**Comment by exmo-dev** [comment]
jquery example only for the protected api, just use $.ajax
