### ISSUE TITLE
Пример запроса

### ISSUE THREAD

**Issue by VenusV** [exmo-dev/exmo_api_lib#15]
Вы не могли бы привести пример создания и отмены ордера в коде питон на эксмо
https://github.com/exmo-dev/exmo_api_lib/blob/master/python/exmo3.py
`import sys
import http.client
import urllib
import json
import hashlib
import hmac
import time

class ExmoAPI:
    def __init__(self, API_KEY, API_SECRET, API_URL = 'api.exmo.me', API_VERSION = 'v1'):
        self.API_URL = API_URL
        self.API_VERSION = API_VERSION
        self.API_KEY = ''
        self.API_SECRET = bytes('', encoding='utf-8')

    def sha512(self, data):
        H = hmac.new(key = self.API_SECRET, digestmod = hashlib.sha512)
        H.update(data.encode('utf-8'))
        return H.hexdigest()

    def api_query(self, api_method, params = {}):
        params['nonce'] = int(round(time.time() * 1000))
        params =  urllib.parse.urlencode(params)

        sign = self.sha512(params)
        headers = {
            "Content-type": "application/x-www-form-urlencoded",
            "Key": self.API_KEY,
            "Sign": sign
        }
        conn = http.client.HTTPSConnection(self.API_URL)
        conn.request("POST", "/" + self.API_VERSION + "/" + api_method, params, headers)
        response = conn.getresponse().read()

        conn.close()

        try:
            obj = json.loads(response.decode('utf-8'))
            if 'error' in obj and obj['error']:
                print(obj['error'])
                raise sys.exit()
            return obj
        except json.decoder.JSONDecodeError:
            print('Error while parsing response:', response)
            raise sys.exit()

quantity = 4

# Example
ExmoAPI_instance = ExmoAPI('YOUR API KEY', 'YOUR API SECRET')
userinfo = ExmoAPI_instance.api_query('user_info')
balanceusd = userinfo['balances']['USD']
balancerub = userinfo['balances']['RUB']
#print(userinfo,type(userinfo),balanceusd,type(balanceusd),balancerub,type(balancerub))
tickerv = ExmoAPI_instance.api_query('ticker')
highv = tickerv['USD_RUB']['high']
#print(highv,type(highv))

def startbot():
    try:
        activeorder = ExmoAPI_instance.api_query('user_open_orders')
        typev = activeorder['USD_RUB']
        orderid = [dic['order_id'] for dic in typev if dic['type'] == 'buy']
        print(orderid,type(orderid))
        orid = int(orderid[0])
        print(orid,type(orid))
        time.sleep(1)
        ExmoAPI_instance.api_query("order_cancel"(order_id = orid))
        #return

    except KeyError as e:
        print("Ордеров нет",e)
    finally:
        print("V")

while True:
    print("Цикл")
    time.sleep(7)
    startbot()`

**Comment by avelrl** [comment]
`print(ExmoAPI_instance.api_query('order_create', {
    "pair": 'DOGE_BTC',
    "quantity":100,
    "price":0.00001,
    "type":"sell"
    })
)`

`print(ExmoAPI_instance.api_query('order_cancel', {
    "order_id": 3063120293
    })
)`

**Comment by exmo-dev** [comment]
done
