### ISSUE TITLE
Make a typed API.

### ISSUE THREAD

**Issue by alexpantyukhin** [exmo-dev/exmo_api_lib#6]
For now the https://github.com/exmo-dev/exmo_api_lib/blob/master/golang/exmo.go is just an example of making an http requests. The suggestion is ot make a go package, which could be imported in the code.

Also need to have typed calling. For example:
```go
exmoAPI := ExmoAPI(key, secret)

userInfo, err := exmoAPI.UserInfo()
if err != nil {
    fmt.Printf("api result: %v\n", result.uid)
}
```

**Comment by VadimInshakov** [comment]
Done in this PR: https://github.com/exmo-dev/exmo_api_lib/pull/19

**Comment by exmo-dev** [comment]
This is not a complete library, but simply examples of how to properly create a signature.
You can create your own library for working with the API in a separate repository.
