### ISSUE TITLE
В json переход на новую строку при получении данных через запрос к API  

### ISSUE THREAD

**Issue by alexanderyegioya** [exmo-dev/exmo_api_lib#8]
Добрый день,
Пытаюсь использовать ваш скрипт на node.js, для метода ticker. Проблема в том, что полученный json нельзя использовать т.к. в нем присутствуют 2-3 перехода на новую строку и формат уже некорректный. 
![image](https://user-images.githubusercontent.com/31897153/34373945-e1359d02-eb10-11e7-8133-bbd32aa31adf.png)

**Comment by VitKlus** [comment]
Уберите все переводы строки перед обработкой json, да и всё.

**Comment by exmo-dev** [comment]
done
